# Generated by Django 4.2.2 on 2023-07-08 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("equipment", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctor",
            name="equipment",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="doctors", to="equipment.equipment"
            ),
        ),
    ]
