# Generated by Django 4.2.2 on 2023-07-08 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("equipment", "0002_doctor_equipment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="equipment",
            name="doctor",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="equipments", to="equipment.doctor"
            ),
        ),
    ]
