# Generated by Django 3.2.19 on 2023-07-13 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authnapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='age',
            field=models.PositiveIntegerField(verbose_name='Տարիք'),
        ),
    ]
