# Generated by Django 3.2.19 on 2023-07-10 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='university',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
