# Generated by Django 3.2.19 on 2023-07-08 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='magnetic_resonance_imaging',
        ),
    ]
