# Generated by Django 3.2.19 on 2023-07-08 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_remove_doctor_magnetic_resonance_imaging'),
        ('examinations', '0002_auto_20230708_1221'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='magnetic_resonance_imaging_1_5t',
            field=models.ManyToManyField(blank=True, null=True, related_name='magnetic_resonance_imaging_1_5t', to='examinations.MagneticResonanceImagingOneFiveTesla'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='magnetic_resonance_imaging_3t',
            field=models.ManyToManyField(blank=True, null=True, related_name='magnetic_resonance_imaging_3t', to='examinations.MagneticResonanceImagingThreeTesla'),
        ),
    ]
