# Generated by Django 3.2.19 on 2023-07-13 20:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('examinations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Քանակ')),
                ('add_datetime', models.DateTimeField(auto_now_add=True, verbose_name='Ավելացման ամսաթիվ')),
                ('computed_tomography', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='examinations.computedtomography')),
                ('magnetic_resonance_imaging_1_5t', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='examinations.magneticresonanceimagingonefivetesla')),
                ('magnetic_resonance_imaging_3t', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='examinations.magneticresonanceimagingthreetesla')),
                ('mammography', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='examinations.mammography')),
                ('ultrasound', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='examinations.ultrasound')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='basket', to=settings.AUTH_USER_MODEL)),
                ('xray', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='examinations.xray')),
            ],
        ),
    ]
