# Generated by Django 4.2.2 on 2023-07-09 08:32

from django.db import migrations, models
import helpers.file_storage


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Doctor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name": "Doctor",
                "verbose_name_plural": "Doctors",
            },
        ),
        migrations.CreateModel(
            name="XRay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=helpers.file_storage.examination_images_storage,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("price", models.FloatField(blank=True, null=True)),
                (
                    "doctor",
                    models.ManyToManyField(
                        blank=True,
                        null=True,
                        related_name="xray",
                        to="examinations.doctor",
                    ),
                ),
            ],
            options={
                "verbose_name": "X-Ray",
                "verbose_name_plural": "X-Rays",
            },
        ),
        migrations.CreateModel(
            name="Ultrasound",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=helpers.file_storage.examination_images_storage,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("price", models.FloatField(blank=True, null=True)),
                (
                    "doctor",
                    models.ManyToManyField(
                        blank=True,
                        null=True,
                        related_name="ultrasound",
                        to="examinations.doctor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ultrasound",
                "verbose_name_plural": "Ultrasounds",
            },
        ),
        migrations.CreateModel(
            name="Mammography",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=helpers.file_storage.examination_images_storage,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("price", models.FloatField(blank=True, null=True)),
                (
                    "doctor",
                    models.ManyToManyField(
                        blank=True,
                        null=True,
                        related_name="mammography",
                        to="examinations.doctor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mammography",
                "verbose_name_plural": "Mammographies",
            },
        ),
        migrations.CreateModel(
            name="MagneticResonanceImagingThreeTesla",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=helpers.file_storage.examination_images_storage,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("price", models.FloatField(blank=True, null=True)),
                (
                    "doctor",
                    models.ManyToManyField(
                        blank=True,
                        null=True,
                        related_name="magnetic_resonance_imaging_3t",
                        to="examinations.doctor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Magnetic Resonance Imaging (3 Tesla)",
                "verbose_name_plural": "Magnetic Resonance Imagings (3 Tesla)",
            },
        ),
        migrations.CreateModel(
            name="MagneticResonanceImagingOneFiveTesla",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=helpers.file_storage.examination_images_storage,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("price", models.FloatField(blank=True, null=True)),
                (
                    "doctor",
                    models.ManyToManyField(
                        blank=True,
                        null=True,
                        related_name="magnetic_resonance_imaging_1_5t",
                        to="examinations.doctor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Magnetic Resonance Imaging (1.5 Tesla)",
                "verbose_name_plural": "Magnetic Resonance Imagings (1.5 Tesla)",
            },
        ),
        migrations.CreateModel(
            name="ComputedTomography",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=helpers.file_storage.examination_images_storage,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("price", models.FloatField(blank=True, null=True)),
                (
                    "doctor",
                    models.ManyToManyField(
                        blank=True,
                        null=True,
                        related_name="computed_tomography",
                        to="examinations.doctor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Computed Tomography",
                "verbose_name_plural": "Computed Tomographies",
            },
        ),
    ]
