# Generated by Django 3.2.19 on 2023-07-08 12:21

from django.db import migrations, models
import helpers.file_storage


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_remove_doctor_magnetic_resonance_imaging'),
        ('examinations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MagneticResonanceImagingOneFiveTesla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=helpers.file_storage.examination_images_storage)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('price', models.FloatField(blank=True, null=True)),
                ('doctor', models.ManyToManyField(blank=True, null=True, related_name='magnetic_resonance_imaging_1_5t', to='examinations.Doctor')),
            ],
            options={
                'verbose_name': 'Magnetic Resonance Imaging (1.5 Tesla)',
                'verbose_name_plural': 'Magnetic Resonance Imagings (1.5 Tesla)',
            },
        ),
        migrations.CreateModel(
            name='MagneticResonanceImagingThreeTesla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=helpers.file_storage.examination_images_storage)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('price', models.FloatField(blank=True, null=True)),
                ('doctor', models.ManyToManyField(blank=True, null=True, related_name='magnetic_resonance_imaging_3t', to='examinations.Doctor')),
            ],
            options={
                'verbose_name': 'Magnetic Resonance Imaging (3 Tesla)',
                'verbose_name_plural': 'Magnetic Resonance Imagings (3 Tesla)',
            },
        ),
        migrations.DeleteModel(
            name='MagneticResonanceImaging',
        ),
    ]
