# Generated by Django 3.2.19 on 2023-07-13 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('examinations', '0002_auto_20230712_1756'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='computedtomography',
            name='readable_name',
        ),
        migrations.RemoveField(
            model_name='magneticresonanceimagingonefivetesla',
            name='readable_name',
        ),
        migrations.RemoveField(
            model_name='magneticresonanceimagingthreetesla',
            name='readable_name',
        ),
        migrations.RemoveField(
            model_name='mammography',
            name='readable_name',
        ),
        migrations.RemoveField(
            model_name='ultrasound',
            name='readable_name',
        ),
        migrations.RemoveField(
            model_name='xray',
            name='readable_name',
        ),
    ]
